# Generated by Django 3.2 on 2021-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowTheBug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='SOME STRING', upload_to='events'),
        ),
    ]
