# Generated by Django 3.2 on 2021-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(default='Krozom', max_length=500),
        ),
    ]
